### ISSUE TITLE
I'd love to use the npm "nougat" name

### ISSUE THREAD

**Issue by tcoulter** [unau/nougat#1]
Hi there,

I'm the creator of [Truffle](http://truffleframework.com), and I have another project I consider to be a "sister application" to Truffle that I'd like to call Nougat. You have the `nougat` name on npm and I was wondering if you're still using it. If not, I would love to use it for mine. Please contact me at tim.coulter@consensys.com for more details, or if you have questions.

Thanks!
Tim

**Comment by unau** [comment]
We regret to inform you that we cannot meet your wish. Our nougat project is still active.
